atenas/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.views.generic import RedirectView, TemplateView
from django.contrib import admin
import os
import django.views
import recuento.views
import comun.views
import verificacion.views
import django.contrib.auth.views

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

admin.autodiscover()

urlpatterns = [
#    url(r'^admin/', include(admin.site.urls)),
#    url("^adminatenas/", include(admin.site.urls)),

    url(r'^atenas/adminatenas/doc/', include('django.contrib.admindocs.urls')),
    url(r'^atenas/adminatenas/', include(admin.site.urls)),
    url(r'^accounts/login/$', django.contrib.auth.views.login),
    url(r'^$', comun.views.selector),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
               
    url(r'^presentacion_60/$', recuento.views.presentacion_60),
    url(r'^presentacion_15/$', recuento.views.presentacion_15),
    url(r'^confirmar_60/$', recuento.views.confirmar_60),
    url(r'^confirmar_15/$', recuento.views.confirmar_15),
    url(r'^alegaciones_60/$', recuento.views.alegaciones_60),
    url(r'^alegaciones_15/$', recuento.views.alegaciones_15),
    url(r'^votacion_60/$', recuento.views.votacion_60),
    url(r'^votacion_15/$', recuento.views.votacion_15),
    url(r'^comision_60/$', recuento.views.comision_60),
    url(r'^comision_15/$', recuento.views.comision_15),
    url(r'^comision_60/(?P<num>\d+)/$', recuento.views.editar_candidato_60),
    url(r'^comision_15/(?P<num>\d+)/$', recuento.views.editar_candidato_15),
    url(r'^resultado_15/$', recuento.views.resultado_15),
    url(r'^resultado_60/$', recuento.views.resultado_60),
    url(r'^ver_candidaturas_60/$', recuento.views.ver_candidatos_60),
    url(r'^ver_candidaturas_15/$', recuento.views.ver_candidatos_15),
    url(r'^envia_clave_60/$', recuento.views.envia_clave_60),
    url(r'^envia_clave_15/$', recuento.views.envia_clave_15),
    url(r'^alegar/(?P<num>\d+)/$', recuento.views.alegar),
    url(r'^alegacion_ok/$', recuento.views.alegacion_ok),
    url(r'^ok_15/$', recuento.views.ok_15),
    url(r'^ok2_15/$', recuento.views.casi_ok_15),
    url(r'^ok_60/$', recuento.views.ok_60),
    url(r'^ok2_60/$', recuento.views.casi_ok_60),
    url(r'^ver_plazos/$', TemplateView.as_view(template_name='no_hay_nada.html'), name='ver_plazos'),
    url(r'^papeleta_60/(?P<ca>\d+)/$', recuento.views.papeleta_usu_60),
    url(r'^papeleta_60/(?P<ca>\d+)/registrar/$', recuento.views.registrar_usu_60),
    url(r'^papeleta_15/(?P<ca>\d+)/$', recuento.views.papeleta_usu_15),
    url(r'^papeleta_15/(?P<ca>\d+)/registrar/$', recuento.views.registrar_usu_15),
    
    url(r'^atenas_15/$', comun.views.atenas_15),
    url(r'^atenas_60/$', comun.views.atenas_60),
    url(r'^atenas_15/recuento/$', recuento.views.selector_15),
    url(r'^atenas_60/recuento/$', recuento.views.selector_60),
    url(r'^atenas_15/papeleta/(?P<ca>\d+)/$', recuento.views.papeleta_admin_15),
    url(r'^atenas_60/papeleta/(?P<ca>\d+)/$', recuento.views.papeleta_admin_60),
    url(r'^atenas_15/papeleta/anular/(?P<ca>\d+)/$', recuento.views.anular_15),
    url(r'^atenas_60/papeleta/(?P<ca>\d+)/registrar/$', recuento.views.registrar_admin_60),
    url(r'^atenas_15/papeleta/(?P<ca>\d+)/registrar/$', recuento.views.registrar_admin_15),
    url(r'^atenas_60/papeleta/anular/(?P<ca>\d+)/$', recuento.views.anular_60),
    url(r'^atenas/login/$', django.contrib.auth.views.login),
    url(r'^atenas/logout/$', django.contrib.auth.views.logout),
    url(r'^atenas_15/verificacion/$', verificacion.views.index_15),
    url(r'^atenas_15/verificacion/registrar/(?P<id_socio>\d+)/$', verificacion.views.registrar_15),
    url(r'^atenas_15/verificacion/registrar/(?P<id_socio>\d+)/ok/$', verificacion.views.registrarOK_15),
    url(r'^atenas_15/verificacion/registroKO/(?P<id_socio>\d+)/$', verificacion.views.registrarKO_15),
    url(r'^atenas_60/verificacion/$', verificacion.views.index_60),
    url(r'^atenas_60/verificacion/registrar/(?P<id_socio>\d+)/$', verificacion.views.registrar_60),
    url(r'^atenas_60/verificacion/registrar/(?P<id_socio>\d+)/ok/$', verificacion.views.registrarOK_60),
    url(r'^atenas_60/verificacion/registroKO/(?P<id_socio>\d+)/$', verificacion.views.registrarKO_60),
]
if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

verificacion/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils.timezone import get_default_timezone

from simple_salesforce import Salesforce

from comun.models import Circunscripcion
from comun import claveAleatoria

params = '''Name Income_ultimos_12_meses_CONSEJO__c
    DNI__c Birthdate AlizeConstituentID__c MailingPostalCode Email
    Fecha_de_antiguedad__c Activation_Date__c s360a__ContactCodes__c
    s360a__ContactType__c'''.split()

comma_params = ','.join(params)

class MultipleContactsError(RuntimeError):
    pass

def searchContacts(search_string):
    sf = Salesforce(**settings.SF_AUTH)
    response = sf.search('''find {{{}}} 
        in name fields 
        returning contact({} 
            where s360a__ContactCodes__c = 'Active Donor')
        limit 100    
        '''.format(search_string, comma_params))
    return response['searchRecords']
    
def getContact(email, dni, return_list=False):
    limit = 100 if return_list else 2
    ret = []
    sf = Salesforce(**settings.SF_AUTH)
    response = sf.query("""
        SELECT {} 
        FROM Contact 
        WHERE Email ='{}'
        AND s360a__ContactCodes__c = 'Active Donor'
        LIMIT {} """.format(comma_params, email, limit));
    objects = response['records']
    if len(objects) == 1 and not return_list:
        return objects[0]
    else:
        ret += objects
    response = sf.query("""
        SELECT {} 
        FROM Contact 
        WHERE DNI__c ='{}'
        AND s360a__ContactCodes__c = 'Active Donor'
        LIMIT {} """.format(comma_params, dni, limit));
    objects = response['records']
    if len(objects) == 1 and not return_list:
        return objects[0]
    else:
        ret += objects
    response = sf.query("""
        SELECT {}
        FROM Contact 
        WHERE DNI__c ='{}'
        AND s360a__ContactCodes__c = 'Active Donor'
        AND  Email ='{}' 
        LIMIT {} """.format(comma_params, dni, email, limit));
    objects = response['records']
    if len(objects) == 1:
        return objects[0]
    else:
        ret += objects
    if ret and not return_list:
        raise MultipleContactsError()
    return ret

class Socio(models.Model):
    nombre=models.CharField(max_length=200, null=True,blank=True)
    apellidos=models.CharField(max_length=200, null=True,blank=True)
    docu_id=models.CharField(max_length=200,blank=True, verbose_name=u'Documento de identidad')
    num_socio=models.CharField(max_length=200, verbose_name=u'Número de socio/a')
    circunscripcion=models.ForeignKey(Circunscripcion, null=True,blank=True, verbose_name=u'Circunscripción')
    fecha_socio=models.DateTimeField(null=True,blank=True, verbose_name=u'Fecha antigüedad')
    fecha_voto=models.DateTimeField(null=True,blank=True)
    fecha_nacimiento=models.DateTimeField(null=True,blank=True)
    circunscripcion_voto=models.ForeignKey(Circunscripcion, null=True,blank=True, related_name='circunscripcion_voto_60')
    usuario=models.ForeignKey(User, null=True, blank=True)
    correo_electronico=models.EmailField(null=True, blank=True, verbose_name=u'Dirección de correo electrónico')
    clave=models.CharField(max_length=50, null=True, blank=True)

    def fecha_voto_legible(self):
        return self.fecha_voto and self.fecha_voto.astimezone(get_default_timezone()).strftime("%H:%M %d-%m-%Y")

    def fecha_nacimiento_legible(self):
        if self.fecha_nacimiento:
            return self.fecha_nacimiento.strftime("%d-%m-%Y")
        return 'n/d'
    def __unicode__(self):
        return u"%s, %s" % (self.apellidos or '',self.nombre or '')

    class Meta:
        permissions = (
            ("can_verify", "Can verify identities of members"),
            ("can_mark_voted", "Can mark a member has voted"),
            ("can_register_ballot", "Can register a ballot"),
        )
        ordering = ('apellidos','nombre')

    def puedeVotar(self, electronica=False):
        if self.fecha_voto:
            return False,'Registrado voto %s' % (self.fecha_voto_legible(),)
        return True, ''

    def registraVoto(self, usuario, circunscripcion_voto=None):
        assert self.puedeVotar()[0]
        self.fecha_voto=datetime.datetime.now()
        self.circunscripcion_voto_id=circunscripcion_voto or self.circunscripcion_id
        self.usuario=usuario
    def desregistraVoto(self):
        assert not self.puedeVotar()[0]
        self.fecha_voto=None
        self.circunscripcion_voto_id=None
        self.usuario=None
    def get_clave(self):
        if not self.clave or not len(self.clave)== settings.LONGITUD_CLAVE:
            self.clave = claveAleatoria()
            self.save()
        return self.clave

    @staticmethod
    def buscaVotante(buscado):
        try:
            info = getContact(buscado, buscado)
            if info:
                num_socio = info[u'AlizeConstituentID__c']
                income = info['Income_ultimos_12_meses_CONSEJO__c']
                fecha_alta = parse_date(info['Activation_Date__c'])
                today = datetime.date.today()
                meses_active = min(12, diff_month(today, fecha_alta)) 
                if income / meses_active < settings.MIN_INCOME / 12:
                    msg = u'''Cuota insuficiente'''
                if fecha_alta > settings.FECHA_CONVOCATORIA:
                    msg = u'''Para poder participar en estas elecciones necesitabas pertenecer a Greenpeace España en el momento de su convocatoria. Te esperamos en las próximas elecciones.'''
                if info['Birthdate']:
                    fecha_nacimiento = parse_date(info['Birthdate'])
                    if fecha_nacimiento > settings.FECHA_MAXIMA_NACIMIENTO:
                        msg = u'''Menor de edad'''
                elif fecha_alta > settings.FECHA_MAXIMA_NACIMIENTO:
                    msg = u'''Sin info fecha nacimiento'''
                soc_local = mv.Socio.objects.filter(num_socio=num_socio).exclude(fecha_voto=None).first()
                if soc_local:
                    msg = u'''El sistema tiene registrado tu voto en {:%d-%m-%Y %H:%M}'''.format(soc_local.fecha_voto)
            else:
                msg = u'''No encontrado'''
        except mv.MultipleContactsError:
            info = None
            msg = u'''Hay más de una persona en nuestra base de datos que cumple esta
            condición.Por favor, ponte en contacto con nuestra oficina,
            teléfono: 900 535 025, correo electrónico: sociasysocios.es@greenpeace.org.
            Cuando esté resuelto, inténtalo de nuevo. Te esperamos.'''

verificacion/views.py
# -*- coding: utf-8 -*-

from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from comun.models import Circunscripcion, Provincia
from verificacion.models import Socio, getContact, searchContacts, MultipleContactsError
from recuento.models import Consejero
from django.shortcuts import render
from django.utils.dateparse import parse_date

@permission_required('verificacion.verify')
def registrar_60(request, id_socio):
    return registrar(request, id_socio, 60, Socio)

@permission_required('verificacion.verify')
def registrar_15(request, id_socio):
    return registrar(request, id_socio, 15, Consejero)

def registrar(request, id_socio, tipo, clase_votante):
    circunscripciones=Circunscripcion.objects.all()
    socio=clase_votante.objects.get(pk=id_socio)
    return render(request, 'registrar.html', locals())

@permission_required('verificacion.can_mark_voted')
def registrarKO_15(request, id_socio):
    return registrarKO(request, id_socio, 15, Consejero)

@permission_required('verificacion.can_mark_voted')
def registrarKO_60(request, id_socio):
    return registrarKO(request, id_socio, 60, Socio)

def registrarKO(request, id_socio, tipo, clase_votante):
    assert request.method=='POST'
    socio=clase_votante.objects.filter(usuario=request.user).order_by('-fecha_voto')[0]
    assert int(id_socio)==socio.id
    socio.desregistraVoto()
    socio.save()
    return HttpResponseRedirect('../../')

@permission_required('verificacion.can_mark_voted')
def registrarOK_15(request, id_socio):
    return registrarOK(request, id_socio, 15, Consejero)

@permission_required('verificacion.can_mark_voted')
def registrarOK_60(request, id_socio):
    return registrarOK(request, id_socio, 60, Socio)

def registrarOK(request, id_socio, tipo, clase_votante):
    assert request.method=='POST'
    socio=clase_votante.objects.get(pk=id_socio)
    circunscripcion_voto=request.POST.get('circunscripcion_voto', 18)
    try:
        socio.registraVoto(request.user, circunscripcion_voto)
    except AssertionError:
        return HttpResponseRedirect('../../')
    socio.save()
    return HttpResponseRedirect('../../../')
    

@permission_required('verificacion.can_verify')
def index_15(request):
    return index(request, 15, Consejero)

@permission_required('verificacion.can_verify')
def index_60(request):
    return index(request, 60, Socio)

def index(request, tipo, clase_votante):
    try:
        ultimosocio=clase_votante.objects.filter(usuario=request.user).order_by('-fecha_voto')[0]
    except IndexError:
        ultimosocio=None
    buscado=request.GET.get('buscado',request.session.get('buscado', '' ))
    if isinstance(buscado,str):
        buscado=unicode(buscado,'utf8')
    buscado=buscado.strip()
    request.session['buscado']=buscado
    buscado=buscado.encode('utf-8')
    if buscado:
        if clase_votante is Socio:
            res = []
            infos = getContact(buscado, buscado, return_list=True)
            if not infos:
                infos = searchContacts(buscado)
            for info in infos:
                num_socio = info[u'AlizeConstituentID__c']
                income = info['Income_ultimos_12_meses_CONSEJO__c']
                fecha_alta = parse_date(info['Activation_Date__c'])
                socio, _ = Socio.objects.get_or_create(num_socio=num_socio)
                socio.correo_electronico = info['Email']
                socio.docu_id = info['DNI__c'] or 'n/a'
                socio.fecha_nacimiento = info['Birthdate']
                socio.nombre = info['Name']
                if info['MailingPostalCode']:
                    prefijo = info['MailingPostalCode'][:2]
                    try:
                        circunscripcion_por_cp = Provincia.objects.get(prefijo_cp=prefijo).circunscripcion
                    except ObjectDoesNotExist:
                        circunscripcion_por_cp = Circunscripcion.objects.get(id=18)
                else:
                    circunscripcion_por_cp = Circunscripcion.objects.get(id=18)
                socio.circunscripcion = circunscripcion_por_cp
                socio.save()
                res.append(socio)
        elif clase_votante is Consejero:
            res=clase_votante.objects
            for palabra in buscado.split():
                res=res.filter(
                    Q(apellidos__unaccent__icontains=palabra)
                    | Q(nombre__unaccent__icontains=palabra)
                )[:100]
    else:
        res=[]
    if tipo == 15:
        circunscripciones=Circunscripcion.objects.filter(pk=18)
    else:
        circunscripciones=Circunscripcion.objects.all()
    c=dict(res=res,
        ultimosocio=ultimosocio,
        buscado=buscado,
        circunscripciones=circunscripciones,
        tipo=tipo,
        )
    return render(request, 'verificacion.html', c)

verificacion/templates/registrar.html
{% extends "base.html" %}

{% block title %}..:: {{user}}@Atenas ::.. validación y registro de votantes/validació i registre de votants{% endblock %}
{% block title2 %}..:: {{user}}@Atenas ::..<br />validación y registro de votantes<br>validació i registre de votants{% endblock %}

{%block body%}
<div style="clear:left;"></div>

detalle/detall
<table border="border">
<tr><td>apellidos / cognoms</td><td>{{socio.apellidos}}</td></td>
<tr><td>nombre / nom</td><td>{{socio.nombre}}</td></td>
<tr><td>número</td><td>{{socio.num_socio}}</td></td>
<tr><td>documento oficial / document oficial</td><td>{{socio.docu_id}}</td></td>
<tr><td>Fecha nacimiento/ XXX</td><td>{{socio.fecha_nacimiento_legible}}</td></td>
<tr><td>circunscripción / circumscripció</td><td><span style="font-size:150%;">{{socio.circunscripcion|default_if_none:"Extranjero"}}</span></td></td>
</table>
{%if socio.puedeVotar.0%}
<form action="./ok/" method="POST" >
{%if socio.circunscripcion == 18 %}
    <select id="id_circunscripcion_voto" class="vNullSelectField" name="circunscripcion_voto" size="1">
        {%for circ in circunscripciones%}
        <option value="{{circ.id}}" >{{circ}}</option>{%endfor%}
    </select>
{% else %}
    <input type="hidden" name="circunscripcion_voto" value="{{socio.circunscripcion.id}}" />
{% endif %}
<input type="submit" value="registrar voto/registrar vot" onclick="return confirm('¿Confirma el voto? {{socio.puedeVotar.1}}')">
{% csrf_token %}
</form>
{% else %}
esta persona no puede votar/aquesta persona no pot votar:<br>
{{ socio.puedeVotar.1}}
{% endif %}
<p><a href="../../">volver a búsqueda/tornar a recerca</a></p>
<p><a href="../../../">volver a menú principal/tornar a menú principal</a></p>
<p><a href="/atenas/logout/?next=/atenas_{{tipo}}/">cerrar sesión/tancar sessió</a></p>

{% endblock %}

verificacion/templates/verificacion.html
{% extends "base.html" %}

{% block title %}..:: {{user}}@Atenas ::.. verificación y registro de votantes/validació i registre de votants{% endblock %}
{% block title2 %}..:: {{user}}@Atenas ::..<br />verificación y registro de votantes<br>validació i registre de votants{% endblock %}

{%block body%}
<div style="float:right; width:30%;">
<table border="border">
        <tr>
        <th>circunscripción<br />circumscripció</th><th>nº papeletas verificadas<br /></th>
        </tr>
        {%for circ in circunscripciones%}
            <tr>
            	<td>{{circ}}</td>
		<td style="text-align:center;">{{circ.cuentaPapeletasVerificadas}}</td>
            </tr>
        {%endfor%}
</table>
</div>
<form action=".">
<input name="buscado" id="buscado" value="{{buscado}}">
<input type="submit" value="buscar">
</form >
<div style="clear:left;"><br/></div>

{% if buscado%}
    {% if res%}
    <table border="1px" >
        <tr>
            <th>apellidos, nombre / cognoms, nom</th>
            <th>nº</th>
            <th>doc. oficial</th>
            <th>circunscripción / circumscripció</th>
            <th>¿puede votar? / pot votar?</th>
        </tr>
        {% for r in res%}
        <tr>
            <td><a href="./registrar/{{r.id}}/">{{r}}</a></td>
            <td> {{r.num_socio}}</td>
            <td> {{r.docu_id}}</td>
            <td> {%if r.circunscripcion%}
                {{r.circunscripcion}}
            {%else%}
                Extranjero
                {%if r.circunscripcion_voto%}
                ({{r.circunscripcion_voto}})
                {%endif%}
            {%endif%}
            </td>
            <td>
            {%if not r.puedeVotar.0%} NO: 
            {%else%}
                {%if not r.puedeVotar.1%}
                    Sí
                {%endif%}
            {%endif%}
            {{r.puedeVotar.1}}
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else%}
    sin resultados/sense resultats
    {% endif %}
{% endif %}
<p/>
<div class="menu" style="clear:both;">
{% if ultimosocio %}
<form action="./registroKO/{{ ultimosocio.id }}/" method="POST">
{% csrf_token %}
    Último voto registrado: {{ ultimosocio }} {{ ultimosocio.num_socio }}
    <input type="submit" value="Anular" 
        onclick="return confirm('¿Confirma la ANULACIÓN del voto?')"
        />
</form>
<br/>
{% endif %}

<a href="/atenas_{{tipo}}/">volver a menú principal/tornar a menú principal</a><br/>
</div >
<div class="menu">
<a href="/atenas/logout/?next=/atenas_{{tipo}}/">cerrar sesión/tancar sessió</a><br>
</div >

{% endblock %}